# Generated by Django 3.0.4 on 2020-05-26 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistics', '0002_auto_20200526_1507'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schoolunitstats',
            options={'verbose_name_plural': 'school unit stats'},
        ),
        migrations.AddField(
            model_name='schoolunitstats',
            name='unfounded_abs_avg_sem2',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schoolunitstats',
            name='avg_sem2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
    ]
