# Generated by Django 3.0.4 on 2020-03-31 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('allows_level_testing', models.BooleanField(default=False)),
                ('allows_thesis', models.BooleanField(default=False)),
                ('allows_simulation', models.BooleanField(default=False)),
                ('allows_exemption', models.BooleanField(default=False)),
                ('is_coordination', models.BooleanField(default=False)),
            ],
        ),
    ]
