# Generated by Django 3.0.4 on 2020-03-31 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic_programs', '0001_initial'),
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramSubjectThrough',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=64)),
                ('class_grade', models.CharField(max_length=3)),
                ('weekly_hours_count', models.PositiveSmallIntegerField()),
                ('is_mandatory', models.BooleanField(default=True)),
                ('academic_program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='program_subjects_through', related_query_name='program_subject_through', to='academic_programs.AcademicProgram')),
                ('generic_academic_program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='program_subjects_through', related_query_name='program_subject_through', to='academic_programs.GenericAcademicProgram')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='program_subjects_through', related_query_name='program_subject_through', to='subjects.Subject')),
            ],
        ),
    ]
