# Generated by Django 3.0.4 on 2020-04-08 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0003_auto_20200331_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='programsubjectthrough',
            name='class_grade_arabic',
            field=models.PositiveSmallIntegerField(default=9),
            preserve_default=False,
        ),
    ]
