# Generated by Django 3.0.4 on 2020-04-08 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0004_programsubjectthrough_class_grade_arabic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ('name',)},
        ),
    ]
