# Generated by Django 3.0.4 on 2020-04-13 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0005_auto_20200408_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programsubjectthrough',
            name='class_grade',
            field=models.CharField(max_length=4),
        ),
    ]
