# Generated by Django 3.0.4 on 2020-04-23 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0005_schoolunitcategory_category_level'),
        ('subjects', '0007_auto_20200416_1432'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorySubjectThrough',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=64)),
                ('class_grade', models.CharField(max_length=4)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_subjects_through', related_query_name='category_subject_through', to='schools.SchoolUnitCategory')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_subjects_through', related_query_name='category_subject_through', to='subjects.Subject')),
            ],
        ),
    ]
