# Generated by Django 3.0.4 on 2020-04-30 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0008_categorysubjectthrough'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='should_be_in_taught_subjects',
            field=models.BooleanField(default=True),
        ),
    ]
