# Generated by Django 3.0.4 on 2020-05-08 13:57

from django.db import migrations
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0010_auto_20200504_1339'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': (django.db.models.functions.text.Lower('name'),)},
        ),
    ]
