# Generated by Django 3.0.4 on 2020-05-18 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0011_auto_20200508_1357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='allows_level_testing',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='allows_simulation',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='allows_thesis',
        ),
    ]
