# Generated by Django 3.0.4 on 2020-05-26 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0012_auto_20200518_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorysubjectthrough',
            name='weekly_hours_count',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
