# Generated by Django 3.0.4 on 2020-05-27 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0013_categorysubjectthrough_weekly_hours_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='programsubjectthrough',
            name='is_core_subject',
            field=models.BooleanField(default=False),
        ),
    ]
