# Generated by Django 3.0.4 on 2020-06-16 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0014_programsubjectthrough_is_core_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programsubjectthrough',
            name='is_core_subject',
        ),
    ]
