from .generic_academic_programs import UnregisteredAcademicProgramList, GenericAcademicProgramList, GenericAcademicProgramDetail
from .academic_programs import AcademicProgramDetail, AcademicProgramList, AcademicProgramSubjectList
