from .student_catalog_per_subject import StudentCatalogPerSubject
from .subject_grade import SubjectGrade
from .subject_absence import SubjectAbsence
from .examination_grade import ExaminationGrade
from .student_catalog_per_year import StudentCatalogPerYear
