FORMAT: 1A
HOST: https://staging.api.edualert.ro

# edualert-API

:[AUTH](auth.apib)

:[MY-ACCOUNT](my-account.apib)

:[USERS](users.apib)

:[ACADEMIC-YEAR-CALENDAR](academic-year-calendar.apib)

:[SCHOOL-UNITS](school-units.apib)

:[ACADEMIC-PROGRAMS](academic-programs.apib)

:[STUDY-CLASSES](study-classes.apib)

:[CATALOG](catalog.apib)

:[SUBJECTS](subjects.apib)

:[MESSAGES](messages.apib)

:[STATISTICS](statistics.apib)

:[STUDENTS-SITUATION](students-situation.apib)

:[DATA STRUCTURES](structures.apib)
