from django.test import SimpleTestCase
from edualert.common.utils import strip_diacritics


class StripAccentsTestCase(SimpleTestCase):
    """
    Test `strip_diacritics` to make sure it alters text as expected.
    """
    def test_strip_diacritics(self):
        for test_case in expected_results:
            if isinstance(test_case, list):
                for inner_test_case in test_case:
                    self._check_test_case(inner_test_case)
            else:
                self._check_test_case(test_case)

    def _check_test_case(self, test_case):
        if test_case['type'] == 'VALUE':
            result = strip_diacritics(test_case['value'])
            expected = test_case['expected']

            # check the result is as expected and provide a useful message in case of failure
            eq_msg = "Equal test failed for '{}' (encoded: '{}'), expected '{}' (encoded: '{}')".format(result, result.encode('ascii', 'backslashreplace'), expected, expected.encode('ascii', 'backslashreplace'))
            self.assertEqual(result, expected, msg=eq_msg)

            # check result is (not) ascii and provide a useful message in case of failure
            ascii_msg = "ASCII test failed for '{}' with expected '{}'".format(result, test_case['expected'])
            self.assertEqual(result.isascii(), test_case['is_ascii'], msg=ascii_msg)
        elif test_case['type'] == 'RANGE':
            start_int = int(test_case['start'], 16)
            end_int = int(test_case['end'], 16)
            for i in range(start_int, end_int + 1):
                character = chr(i)
                self.assertEqual(character, strip_diacritics(character))


def create_expected_val_test(value, expected, is_ascii=False):
    """The provided value is expected to be changed to the expected value."""
    return {'type': 'VALUE', 'value': value, 'expected': expected, 'is_ascii': is_ascii}


def create_unchanged_range_test(start, end):
    """Characters in the specified range are expected to remain the same."""
    return {'type': 'RANGE', 'start': start, 'end': end}


def create_combined_test(char, start, end):
    start_int = int(start, 16)
    end_int = int(end, 16)

    tests = []
    for i in range(start_int, end_int + 1):
        string = char + chr(i)
        tests.append(create_expected_val_test(string, char, is_ascii=True))
    return tests


# Expected results for diacritics removal group by unicode code blocks.
expected_results = [
    #
    # Code block: Basic Latin (ASCII); U+0000 - U+007F
    #
    create_unchanged_range_test('0000', '007F'),
    #
    # Code block: Latin-1 Supplement; U+0080 - U+00FF
    #
    create_unchanged_range_test('0080', '009F'),  # control characters
    create_expected_val_test('¡', '¡'),
    create_expected_val_test('¢', '¢'),
    create_expected_val_test('£', '£'),
    create_expected_val_test('¤', '¤'),
    create_expected_val_test('¥', '¥'),
    create_expected_val_test('¦', '¦'),
    create_expected_val_test('§', '§'),
    create_expected_val_test('¨', '¨'),
    create_expected_val_test('©', '©'),
    create_expected_val_test('ª', 'ª'),
    create_expected_val_test('«', '«'),
    create_expected_val_test('¬', '¬'),
    create_expected_val_test('\u00AD', '\u00AD'),  # Soft hyphen
    create_expected_val_test('®', '®'),
    create_expected_val_test('¯', '¯'),
    create_expected_val_test('°', '°'),
    create_expected_val_test('±', '±'),
    create_expected_val_test('²', '²'),
    create_expected_val_test('³', '³'),
    create_expected_val_test('´', '´'),
    create_expected_val_test('µ', 'µ'),
    create_expected_val_test('¶', '¶'),
    create_expected_val_test('·', '·'),
    create_expected_val_test('¸', '¸'),
    create_expected_val_test('¹', '¹'),
    create_expected_val_test('º', 'º'),
    create_expected_val_test('»', '»'),
    create_expected_val_test('¼', '¼'),
    create_expected_val_test('½', '½'),
    create_expected_val_test('¾', '¾'),
    create_expected_val_test('¿', '¿'),
    create_expected_val_test('À', 'A', is_ascii=True),
    create_expected_val_test('Á', 'A', is_ascii=True),
    create_expected_val_test('Â', 'A', is_ascii=True),
    create_expected_val_test('Ã', 'A', is_ascii=True),
    create_expected_val_test('Ä', 'A', is_ascii=True),
    create_expected_val_test('Å', 'A', is_ascii=True),
    create_expected_val_test('Æ', 'Æ'),
    create_expected_val_test('Ç', 'C', is_ascii=True),
    create_expected_val_test('È', 'E', is_ascii=True),
    create_expected_val_test('É', 'E', is_ascii=True),
    create_expected_val_test('Ê', 'E', is_ascii=True),
    create_expected_val_test('Ë', 'E', is_ascii=True),
    create_expected_val_test('Ì', 'I', is_ascii=True),
    create_expected_val_test('Í', 'I', is_ascii=True),
    create_expected_val_test('Î', 'I', is_ascii=True),
    create_expected_val_test('Ï', 'I', is_ascii=True),
    create_expected_val_test('Ð', 'Ð'),
    create_expected_val_test('Ñ', 'N', is_ascii=True),
    create_expected_val_test('Ò', 'O', is_ascii=True),
    create_expected_val_test('Ó', 'O', is_ascii=True),
    create_expected_val_test('Ô', 'O', is_ascii=True),
    create_expected_val_test('Õ', 'O', is_ascii=True),
    create_expected_val_test('Ö', 'O', is_ascii=True),
    create_expected_val_test('×', '×'),
    create_expected_val_test('Ø', 'Ø'),
    create_expected_val_test('Ù', 'U', is_ascii=True),
    create_expected_val_test('Ú', 'U', is_ascii=True),
    create_expected_val_test('Û', 'U', is_ascii=True),
    create_expected_val_test('Ü', 'U', is_ascii=True),
    create_expected_val_test('Ý', 'Y', is_ascii=True),
    create_expected_val_test('Þ', 'Þ'),
    create_expected_val_test('ß', 'ß'),
    create_expected_val_test('à', 'a', is_ascii=True),
    create_expected_val_test('á', 'a', is_ascii=True),
    create_expected_val_test('â', 'a', is_ascii=True),
    create_expected_val_test('ã', 'a', is_ascii=True),
    create_expected_val_test('ä', 'a', is_ascii=True),
    create_expected_val_test('å', 'a', is_ascii=True),
    create_expected_val_test('æ', 'æ'),
    create_expected_val_test('ç', 'c', is_ascii=True),
    create_expected_val_test('è', 'e', is_ascii=True),
    create_expected_val_test('é', 'e', is_ascii=True),
    create_expected_val_test('ê', 'e', is_ascii=True),
    create_expected_val_test('ë', 'e', is_ascii=True),
    create_expected_val_test('ì', 'i', is_ascii=True),
    create_expected_val_test('í', 'i', is_ascii=True),
    create_expected_val_test('î', 'i', is_ascii=True),
    create_expected_val_test('ï', 'i', is_ascii=True),
    create_expected_val_test('ð', 'ð'),
    create_expected_val_test('ñ', 'n', is_ascii=True),
    create_expected_val_test('ò', 'o', is_ascii=True),
    create_expected_val_test('ó', 'o', is_ascii=True),
    create_expected_val_test('ô', 'o', is_ascii=True),
    create_expected_val_test('õ', 'o', is_ascii=True),
    create_expected_val_test('ö', 'o', is_ascii=True),
    create_expected_val_test('÷', '÷'),
    create_expected_val_test('ø', 'ø'),
    create_expected_val_test('ù', 'u', is_ascii=True),
    create_expected_val_test('ú', 'u', is_ascii=True),
    create_expected_val_test('û', 'u', is_ascii=True),
    create_expected_val_test('ü', 'u', is_ascii=True),
    create_expected_val_test('ý', 'y', is_ascii=True),
    create_expected_val_test('þ', 'þ'),
    #
    # Code block: Latin Extended-A; U+0100 - U+017F
    #
    create_expected_val_test('Ā', 'A', is_ascii=True),
    create_expected_val_test('ā', 'a', is_ascii=True),
    create_expected_val_test('Ă', 'A', is_ascii=True),
    create_expected_val_test('ă', 'a', is_ascii=True),
    create_expected_val_test('Ą', 'A', is_ascii=True),
    create_expected_val_test('ą', 'a', is_ascii=True),
    create_expected_val_test('Ć', 'C', is_ascii=True),
    create_expected_val_test('ć', 'c', is_ascii=True),
    create_expected_val_test('Ĉ', 'C', is_ascii=True),
    create_expected_val_test('ĉ', 'c', is_ascii=True),
    create_expected_val_test('Ċ', 'C', is_ascii=True),
    create_expected_val_test('ċ', 'c', is_ascii=True),
    create_expected_val_test('Č', 'C', is_ascii=True),
    create_expected_val_test('č', 'c', is_ascii=True),
    create_expected_val_test('Ď', 'D', is_ascii=True),
    create_expected_val_test('ď', 'd', is_ascii=True),
    create_expected_val_test('Đ', 'Đ'),
    create_expected_val_test('đ', 'đ'),
    create_expected_val_test('Ē', 'E', is_ascii=True),
    create_expected_val_test('ē', 'e', is_ascii=True),
    create_expected_val_test('Ĕ', 'E', is_ascii=True),
    create_expected_val_test('ĕ', 'e', is_ascii=True),
    create_expected_val_test('Ė', 'E', is_ascii=True),
    create_expected_val_test('ė', 'e', is_ascii=True),
    create_expected_val_test('Ę', 'E', is_ascii=True),
    create_expected_val_test('ę', 'e', is_ascii=True),
    create_expected_val_test('Ě', 'E', is_ascii=True),
    create_expected_val_test('ě', 'e', is_ascii=True),
    create_expected_val_test('Ĝ', 'G', is_ascii=True),
    create_expected_val_test('ĝ', 'g', is_ascii=True),
    create_expected_val_test('Ğ', 'G', is_ascii=True),
    create_expected_val_test('ğ', 'g', is_ascii=True),
    create_expected_val_test('Ġ', 'G', is_ascii=True),
    create_expected_val_test('ġ', 'g', is_ascii=True),
    create_expected_val_test('Ģ', 'G', is_ascii=True),
    create_expected_val_test('ģ', 'g', is_ascii=True),
    create_expected_val_test('Ĥ', 'H', is_ascii=True),
    create_expected_val_test('ĥ', 'h', is_ascii=True),
    create_expected_val_test('Ħ', 'Ħ'),
    create_expected_val_test('ħ', 'ħ'),
    create_expected_val_test('Ĩ', 'I', is_ascii=True),
    create_expected_val_test('ĩ', 'i', is_ascii=True),
    create_expected_val_test('Ī', 'I', is_ascii=True),
    create_expected_val_test('ī', 'i', is_ascii=True),
    create_expected_val_test('Ĭ', 'I', is_ascii=True),
    create_expected_val_test('ĭ', 'i', is_ascii=True),
    create_expected_val_test('Į', 'I', is_ascii=True),
    create_expected_val_test('į', 'i', is_ascii=True),
    create_expected_val_test('İ', 'I', is_ascii=True),
    create_expected_val_test('ı', 'ı'),
    create_expected_val_test('Ĳ', 'Ĳ'),
    create_expected_val_test('ĳ', 'ĳ'),
    create_expected_val_test('Ĵ', 'J', is_ascii=True),
    create_expected_val_test('ĵ', 'j', is_ascii=True),
    create_expected_val_test('Ķ', 'K', is_ascii=True),
    create_expected_val_test('ķ', 'k', is_ascii=True),
    create_expected_val_test('ĸ', 'ĸ'),
    create_expected_val_test('Ĺ', 'L', is_ascii=True),
    create_expected_val_test('ĺ', 'l', is_ascii=True),
    create_expected_val_test('Ļ', 'L', is_ascii=True),
    create_expected_val_test('ļ', 'l', is_ascii=True),
    create_expected_val_test('Ľ', 'L', is_ascii=True),
    create_expected_val_test('ľ', 'l', is_ascii=True),
    create_expected_val_test('Ŀ', 'Ŀ'),
    create_expected_val_test('ŀ', 'ŀ'),
    create_expected_val_test('Ł', 'Ł'),
    create_expected_val_test('ł', 'ł'),
    create_expected_val_test('Ń', 'N', is_ascii=True),
    create_expected_val_test('ń', 'n', is_ascii=True),
    create_expected_val_test('Ņ', 'N', is_ascii=True),
    create_expected_val_test('ņ', 'n', is_ascii=True),
    create_expected_val_test('Ň', 'N', is_ascii=True),
    create_expected_val_test('ň', 'n', is_ascii=True),
    create_expected_val_test('ŉ', 'ŉ'),
    create_expected_val_test('Ŋ', 'Ŋ'),
    create_expected_val_test('ŋ', 'ŋ'),
    create_expected_val_test('Ō', 'O', is_ascii=True),
    create_expected_val_test('ō', 'o', is_ascii=True),
    create_expected_val_test('Ŏ', 'O', is_ascii=True),
    create_expected_val_test('ŏ', 'o', is_ascii=True),
    create_expected_val_test('Ő', 'O', is_ascii=True),
    create_expected_val_test('ő', 'o', is_ascii=True),
    create_expected_val_test('Œ', 'Œ'),
    create_expected_val_test('œ', 'œ'),
    create_expected_val_test('Ŕ', 'R', is_ascii=True),
    create_expected_val_test('ŕ', 'r', is_ascii=True),
    create_expected_val_test('Ŗ', 'R', is_ascii=True),
    create_expected_val_test('ŗ', 'r', is_ascii=True),
    create_expected_val_test('Ř', 'R', is_ascii=True),
    create_expected_val_test('ř', 'r', is_ascii=True),
    create_expected_val_test('Ś', 'S', is_ascii=True),
    create_expected_val_test('ś', 's', is_ascii=True),
    create_expected_val_test('Ŝ', 'S', is_ascii=True),
    create_expected_val_test('ŝ', 's', is_ascii=True),
    create_expected_val_test('Ş', 'S', is_ascii=True),
    create_expected_val_test('ş', 's', is_ascii=True),
    create_expected_val_test('Š', 'S', is_ascii=True),
    create_expected_val_test('š', 's', is_ascii=True),
    create_expected_val_test('Ţ', 'T', is_ascii=True),
    create_expected_val_test('ţ', 't', is_ascii=True),
    create_expected_val_test('Ť', 'T', is_ascii=True),
    create_expected_val_test('ť', 't', is_ascii=True),
    create_expected_val_test('Ŧ', 'Ŧ'),
    create_expected_val_test('ŧ', 'ŧ'),
    create_expected_val_test('Ũ', 'U', is_ascii=True),
    create_expected_val_test('ũ', 'u', is_ascii=True),
    create_expected_val_test('Ū', 'U', is_ascii=True),
    create_expected_val_test('ū', 'u', is_ascii=True),
    create_expected_val_test('Ŭ', 'U', is_ascii=True),
    create_expected_val_test('ŭ', 'u', is_ascii=True),
    create_expected_val_test('Ů', 'U', is_ascii=True),
    create_expected_val_test('ů', 'u', is_ascii=True),
    create_expected_val_test('Ű', 'U', is_ascii=True),
    create_expected_val_test('ű', 'u', is_ascii=True),
    create_expected_val_test('Ų', 'U', is_ascii=True),
    create_expected_val_test('ų', 'u', is_ascii=True),
    create_expected_val_test('Ŵ', 'W', is_ascii=True),
    create_expected_val_test('ŵ', 'w', is_ascii=True),
    create_expected_val_test('Ŷ', 'Y', is_ascii=True),
    create_expected_val_test('ŷ', 'y', is_ascii=True),
    create_expected_val_test('Ÿ', 'Y', is_ascii=True),
    create_expected_val_test('Ź', 'Z', is_ascii=True),
    create_expected_val_test('ź', 'z', is_ascii=True),
    create_expected_val_test('Ż', 'Z', is_ascii=True),
    create_expected_val_test('ż', 'z', is_ascii=True),
    create_expected_val_test('Ž', 'Z', is_ascii=True),
    create_expected_val_test('ž', 'z', is_ascii=True),
    #
    # Code block: Latin Extended-B; U+0180 - U+024F
    #
    create_expected_val_test('ƀ', 'ƀ'),
    create_expected_val_test('Ɓ', 'Ɓ'),
    create_expected_val_test('Ƃ', 'Ƃ'),
    create_expected_val_test('ƃ', 'ƃ'),
    create_expected_val_test('Ƅ', 'Ƅ'),
    create_expected_val_test('ƅ', 'ƅ'),
    create_expected_val_test('Ɔ', 'Ɔ'),
    create_expected_val_test('Ƈ', 'Ƈ'),
    create_expected_val_test('ƈ', 'ƈ'),
    create_expected_val_test('Ɖ', 'Ɖ'),
    create_expected_val_test('Ɗ', 'Ɗ'),
    create_expected_val_test('Ƌ', 'Ƌ'),
    create_expected_val_test('ƌ', 'ƌ'),
    create_expected_val_test('ƍ', 'ƍ'),
    create_expected_val_test('Ǝ', 'Ǝ'),
    create_expected_val_test('Ə', 'Ə'),
    create_expected_val_test('Ɛ', 'Ɛ'),
    create_expected_val_test('Ƒ', 'Ƒ'),
    create_expected_val_test('ƒ', 'ƒ'),
    create_expected_val_test('Ɠ', 'Ɠ'),
    create_expected_val_test('Ɣ', 'Ɣ'),
    create_expected_val_test('ƕ', 'ƕ'),
    create_expected_val_test('Ɩ', 'Ɩ'),
    create_expected_val_test('Ɨ', 'Ɨ'),
    create_expected_val_test('Ƙ', 'Ƙ'),
    create_expected_val_test('ƙ', 'ƙ'),
    create_expected_val_test('ƚ', 'ƚ'),
    create_expected_val_test('ƛ', 'ƛ'),
    create_expected_val_test('Ɯ', 'Ɯ'),
    create_expected_val_test('Ɲ', 'Ɲ'),
    create_expected_val_test('ƞ', 'ƞ'),
    create_expected_val_test('Ɵ', 'Ɵ'),
    create_expected_val_test('Ơ', 'O', is_ascii=True),
    create_expected_val_test('ơ', 'o', is_ascii=True),
    create_expected_val_test('Ƣ', 'Ƣ'),
    create_expected_val_test('ƣ', 'ƣ'),
    create_expected_val_test('Ƥ', 'Ƥ'),
    create_expected_val_test('ƥ', 'ƥ'),
    create_expected_val_test('Ʀ', 'Ʀ'),
    create_expected_val_test('Ƨ', 'Ƨ'),
    create_expected_val_test('ƨ', 'ƨ'),
    create_expected_val_test('Ʃ', 'Ʃ'),
    create_expected_val_test('ƪ', 'ƪ'),
    create_expected_val_test('ƫ', 'ƫ'),
    create_expected_val_test('Ƭ', 'Ƭ'),
    create_expected_val_test('ƭ', 'ƭ'),
    create_expected_val_test('Ʈ', 'Ʈ'),
    create_expected_val_test('Ư', 'U', is_ascii=True),
    create_expected_val_test('ư', 'u', is_ascii=True),
    create_expected_val_test('Ʊ', 'Ʊ'),
    create_expected_val_test('Ʋ', 'Ʋ'),
    create_expected_val_test('Ƴ', 'Ƴ'),
    create_expected_val_test('ƴ', 'ƴ'),
    create_expected_val_test('Ƶ', 'Ƶ'),
    create_expected_val_test('ƶ', 'ƶ'),
    create_expected_val_test('Ʒ', 'Ʒ'),
    create_expected_val_test('Ƹ', 'Ƹ'),
    create_expected_val_test('ƹ', 'ƹ'),
    create_expected_val_test('ƺ', 'ƺ'),
    create_expected_val_test('ƻ', 'ƻ'),
    create_expected_val_test('Ƽ', 'Ƽ'),
    create_expected_val_test('ƽ', 'ƽ'),
    create_expected_val_test('ƾ', 'ƾ'),
    create_expected_val_test('ƿ', 'ƿ'),
    create_expected_val_test('ǀ', 'ǀ'),
    create_expected_val_test('ǁ', 'ǁ'),
    create_expected_val_test('ǂ', 'ǂ'),
    create_expected_val_test('ǃ', 'ǃ'),
    create_expected_val_test('Ǆ', 'Ǆ'),
    create_expected_val_test('ǅ', 'ǅ'),
    create_expected_val_test('ǆ', 'ǆ'),
    create_expected_val_test('Ǉ', 'Ǉ'),
    create_expected_val_test('ǈ', 'ǈ'),
    create_expected_val_test('ǉ', 'ǉ'),
    create_expected_val_test('Ǌ', 'Ǌ'),
    create_expected_val_test('ǋ', 'ǋ'),
    create_expected_val_test('ǌ', 'ǌ'),
    create_expected_val_test('Ǎ', 'A', is_ascii=True),
    create_expected_val_test('ǎ', 'a', is_ascii=True),
    create_expected_val_test('Ǐ', 'I', is_ascii=True),
    create_expected_val_test('ǐ', 'i', is_ascii=True),
    create_expected_val_test('Ǒ', 'O', is_ascii=True),
    create_expected_val_test('ǒ', 'o', is_ascii=True),
    create_expected_val_test('Ǔ', 'U', is_ascii=True),
    create_expected_val_test('ǔ', 'u', is_ascii=True),
    create_expected_val_test('Ǖ', 'U', is_ascii=True),
    create_expected_val_test('ǖ', 'u', is_ascii=True),
    create_expected_val_test('Ǘ', 'U', is_ascii=True),
    create_expected_val_test('ǘ', 'u', is_ascii=True),
    create_expected_val_test('Ǚ', 'U', is_ascii=True),
    create_expected_val_test('ǚ', 'u', is_ascii=True),
    create_expected_val_test('Ǜ', 'U', is_ascii=True),
    create_expected_val_test('ǜ', 'u', is_ascii=True),
    create_expected_val_test('ǝ', 'ǝ'),
    create_expected_val_test('Ǟ', 'A', is_ascii=True),
    create_expected_val_test('ǟ', 'a', is_ascii=True),
    create_expected_val_test('Ǡ', 'A', is_ascii=True),
    create_expected_val_test('ǡ', 'a', is_ascii=True),
    create_expected_val_test('Ǣ', 'Æ'),
    create_expected_val_test('ǣ', 'æ'),
    create_expected_val_test('Ǥ', 'Ǥ'),
    create_expected_val_test('ǥ', 'ǥ'),
    create_expected_val_test('Ǧ', 'G', is_ascii=True),
    create_expected_val_test('ǧ', 'g', is_ascii=True),
    create_expected_val_test('Ǩ', 'K', is_ascii=True),
    create_expected_val_test('ǩ', 'k', is_ascii=True),
    create_expected_val_test('Ǫ', 'O', is_ascii=True),
    create_expected_val_test('ǫ', 'o', is_ascii=True),
    create_expected_val_test('Ǭ', 'O', is_ascii=True),
    create_expected_val_test('ǭ', 'o', is_ascii=True),
    create_expected_val_test('Ǯ', 'Ʒ'),
    create_expected_val_test('ǯ', 'ʒ'),
    create_expected_val_test('ǰ', 'j', is_ascii=True),
    create_expected_val_test('Ǳ', 'Ǳ'),
    create_expected_val_test('ǲ', 'ǲ'),
    create_expected_val_test('ǳ', 'ǳ'),
    create_expected_val_test('Ǵ', 'G', is_ascii=True),
    create_expected_val_test('ǵ', 'g', is_ascii=True),
    create_expected_val_test('Ƕ', 'Ƕ'),
    create_expected_val_test('Ƿ', 'Ƿ'),
    create_expected_val_test('Ǹ', 'N', is_ascii=True),
    create_expected_val_test('ǹ', 'n', is_ascii=True),
    create_expected_val_test('Ǻ', 'A', is_ascii=True),
    create_expected_val_test('ǻ', 'a', is_ascii=True),
    create_expected_val_test('Ǽ', 'Æ'),
    create_expected_val_test('ǽ', 'æ'),
    create_expected_val_test('Ǿ', 'Ø'),
    create_expected_val_test('ǿ', 'ø'),
    create_expected_val_test('Ȁ', 'A', is_ascii=True),
    create_expected_val_test('ȁ', 'a', is_ascii=True),
    create_expected_val_test('Ȃ', 'A', is_ascii=True),
    create_expected_val_test('ȃ', 'a', is_ascii=True),
    create_expected_val_test('Ȅ', 'E', is_ascii=True),
    create_expected_val_test('ȅ', 'e', is_ascii=True),
    create_expected_val_test('Ȇ', 'E', is_ascii=True),
    create_expected_val_test('ȇ', 'e', is_ascii=True),
    create_expected_val_test('Ȉ', 'I', is_ascii=True),
    create_expected_val_test('ȉ', 'i', is_ascii=True),
    create_expected_val_test('Ȋ', 'I', is_ascii=True),
    create_expected_val_test('ȋ', 'i', is_ascii=True),
    create_expected_val_test('Ȍ', 'O', is_ascii=True),
    create_expected_val_test('ȍ', 'o', is_ascii=True),
    create_expected_val_test('Ȏ', 'O', is_ascii=True),
    create_expected_val_test('ȏ', 'o', is_ascii=True),
    create_expected_val_test('Ȑ', 'R', is_ascii=True),
    create_expected_val_test('ȑ', 'r', is_ascii=True),
    create_expected_val_test('Ȓ', 'R', is_ascii=True),
    create_expected_val_test('ȓ', 'r', is_ascii=True),
    create_expected_val_test('Ȕ', 'U', is_ascii=True),
    create_expected_val_test('ȕ', 'u', is_ascii=True),
    create_expected_val_test('Ȗ', 'U', is_ascii=True),
    create_expected_val_test('ȗ', 'u', is_ascii=True),
    create_expected_val_test('Ș', 'S', is_ascii=True),
    create_expected_val_test('ș', 's', is_ascii=True),
    create_expected_val_test('Ț', 'T', is_ascii=True),
    create_expected_val_test('ț', 't', is_ascii=True),
    create_expected_val_test('Ȝ', 'Ȝ'),
    create_expected_val_test('ȝ', 'ȝ'),
    create_expected_val_test('Ȟ', 'H', is_ascii=True),
    create_expected_val_test('ȟ', 'h', is_ascii=True),
    create_expected_val_test('Ƞ', 'Ƞ'),
    create_expected_val_test('ȡ', 'ȡ'),
    create_expected_val_test('Ȣ', 'Ȣ'),
    create_expected_val_test('ȣ', 'ȣ'),
    create_expected_val_test('Ȥ', 'Ȥ'),
    create_expected_val_test('ȥ', 'ȥ'),
    create_expected_val_test('Ȧ', 'A', is_ascii=True),
    create_expected_val_test('ȧ', 'a', is_ascii=True),
    create_expected_val_test('Ȩ', 'E', is_ascii=True),
    create_expected_val_test('ȩ', 'e', is_ascii=True),
    create_expected_val_test('Ȫ', 'O', is_ascii=True),
    create_expected_val_test('ȫ', 'o', is_ascii=True),
    create_expected_val_test('Ȭ', 'O', is_ascii=True),
    create_expected_val_test('ȭ', 'o', is_ascii=True),
    create_expected_val_test('Ȯ', 'O', is_ascii=True),
    create_expected_val_test('ȯ', 'o', is_ascii=True),
    create_expected_val_test('Ȱ', 'O', is_ascii=True),
    create_expected_val_test('ȱ', 'o', is_ascii=True),
    create_expected_val_test('Ȳ', 'Y', is_ascii=True),
    create_expected_val_test('ȳ', 'y', is_ascii=True),
    create_expected_val_test('ȴ', 'ȴ'),
    create_expected_val_test('ȵ', 'ȵ'),
    create_expected_val_test('ȶ', 'ȶ'),
    create_expected_val_test('ȷ', 'ȷ'),
    create_expected_val_test('ȸ', 'ȸ'),
    create_expected_val_test('ȹ', 'ȹ'),
    create_expected_val_test('Ⱥ', 'Ⱥ'),
    create_expected_val_test('Ȼ', 'Ȼ'),
    create_expected_val_test('ȼ', 'ȼ'),
    create_expected_val_test('Ƚ', 'Ƚ'),
    create_expected_val_test('Ⱦ', 'Ⱦ'),
    create_expected_val_test('ȿ', 'ȿ'),
    create_expected_val_test('ɀ', 'ɀ'),
    create_expected_val_test('Ɂ', 'Ɂ'),
    create_expected_val_test('ɂ', 'ɂ'),
    create_expected_val_test('Ƀ', 'Ƀ'),
    create_expected_val_test('Ʉ', 'Ʉ'),
    create_expected_val_test('Ʌ', 'Ʌ'),
    create_expected_val_test('Ɇ', 'Ɇ'),
    create_expected_val_test('ɇ', 'ɇ'),
    create_expected_val_test('Ɉ', 'Ɉ'),
    create_expected_val_test('ɉ', 'ɉ'),
    create_expected_val_test('Ɋ', 'Ɋ'),
    create_expected_val_test('ɋ', 'ɋ'),
    create_expected_val_test('Ɍ', 'Ɍ'),
    create_expected_val_test('ɍ', 'ɍ'),
    create_expected_val_test('Ɏ', 'Ɏ'),
    #
    # Code block: IPA Extensions; U+0250 - U+02AF
    #
    create_unchanged_range_test('0250', '02AF'),
    #
    # Code block: Spacing Modifier Letters; U+02B0 - U+02FF
    #
    create_unchanged_range_test('02B0', '02FF'),
    #
    # Code block: Combining Diacritical Marks; U+0300 - U+036F
    #
    create_combined_test('a', '0300', '036F'),
    create_combined_test('A', '0300', '036F'),
    #
    # Skipped code blocks: Greek and Coptic, Cyrillic, Cyrillic Supplement, Armenian, Hebrew, Arabic, Syriac,
    # Arabic Supplement, Thaana, NKo, Samaritan, Mandaic, Syriac Supplement, Arabic Extended-A, Devanagari, Bengali,
    # Gurmukhi, Gujarati, Oriya, Tamil, Telugu, Kannada, Malayalam, Sinhala, Thai, Lao, Tibetan, Myanmar, Georgian,
    # Hangul Jamo, Ethiopic, Ethiopic Supplement, Cherokee, Unified Canadian Aboriginal Syllabics, Ogham, Runic,
    # Tagalog, Hanunoo, Buhid, Tagbanwa, Khmer, Mongolian, Unified Canadian Aboriginal Syllabics Extended, Limbu,
    # Tai Le, New Tai Lue, Khmer Symbols, Buginese, Tai Tham; U+0370 - U+1AAF
    #
    #
    # Code block: Combining Diacritical Marks Extended; U+1AB0 - U+1AFF
    #
    create_combined_test('a', '1AB0', '1ABD'),
    create_expected_val_test('a\u1ABE', 'a\u1ABE'),
    create_expected_val_test('a\u1ABF', 'a\u1ABF'),
    create_expected_val_test('a\u1AC0', 'a\u1AC0'),
    #
    # Skipped code blocks: Balinese, Sundanese, Batak, Lepcha, Ol Chiki, Cyrillic Extended-C, Georgian Extended,
    # Sundanese Supplement, Vedic Extensions, Phonetic Extensions, Phonetic Extensions Supplement; U+1B00 - U+1DBF
    #
    #
    # Code block: Combining Diacritical Marks Supplement; U+1DC0 - U+1DFF
    #
    create_combined_test('a', '1DC0', '1DF9'),
    # skipped unassigned U+1DFA
    create_combined_test('a', '1DFB', '1DFF'),
    #
    # Code block: Latin Extended Additional; U+1E00 - U+1EFF
    #
    create_expected_val_test('Ḁ', 'A', is_ascii=True),
    create_expected_val_test('ḁ', 'a', is_ascii=True),
    create_expected_val_test('Ḃ', 'B', is_ascii=True),
    create_expected_val_test('ḃ', 'b', is_ascii=True),
    create_expected_val_test('Ḅ', 'B', is_ascii=True),
    create_expected_val_test('ḅ', 'b', is_ascii=True),
    create_expected_val_test('Ḇ', 'B', is_ascii=True),
    create_expected_val_test('ḇ', 'b', is_ascii=True),
    create_expected_val_test('Ḉ', 'C', is_ascii=True),
    create_expected_val_test('ḉ', 'c', is_ascii=True),
    create_expected_val_test('Ḋ', 'D', is_ascii=True),
    create_expected_val_test('ḋ', 'd', is_ascii=True),
    create_expected_val_test('Ḍ', 'D', is_ascii=True),
    create_expected_val_test('ḍ', 'd', is_ascii=True),
    create_expected_val_test('Ḏ', 'D', is_ascii=True),
    create_expected_val_test('ḏ', 'd', is_ascii=True),
    create_expected_val_test('Ḑ', 'D', is_ascii=True),
    create_expected_val_test('ḑ', 'd', is_ascii=True),
    create_expected_val_test('Ḓ', 'D', is_ascii=True),
    create_expected_val_test('ḓ', 'd', is_ascii=True),
    create_expected_val_test('Ḕ', 'E', is_ascii=True),
    create_expected_val_test('ḕ', 'e', is_ascii=True),
    create_expected_val_test('Ḗ', 'E', is_ascii=True),
    create_expected_val_test('ḗ', 'e', is_ascii=True),
    create_expected_val_test('Ḙ', 'E', is_ascii=True),
    create_expected_val_test('ḙ', 'e', is_ascii=True),
    create_expected_val_test('Ḛ', 'E', is_ascii=True),
    create_expected_val_test('ḛ', 'e', is_ascii=True),
    create_expected_val_test('Ḝ', 'E', is_ascii=True),
    create_expected_val_test('ḝ', 'e', is_ascii=True),
    create_expected_val_test('Ḟ', 'F', is_ascii=True),
    create_expected_val_test('ḟ', 'f', is_ascii=True),
    create_expected_val_test('Ḡ', 'G', is_ascii=True),
    create_expected_val_test('ḡ', 'g', is_ascii=True),
    create_expected_val_test('Ḣ', 'H', is_ascii=True),
    create_expected_val_test('ḣ', 'h', is_ascii=True),
    create_expected_val_test('Ḥ', 'H', is_ascii=True),
    create_expected_val_test('ḥ', 'h', is_ascii=True),
    create_expected_val_test('Ḧ', 'H', is_ascii=True),
    create_expected_val_test('ḧ', 'h', is_ascii=True),
    create_expected_val_test('Ḩ', 'H', is_ascii=True),
    create_expected_val_test('ḩ', 'h', is_ascii=True),
    create_expected_val_test('Ḫ', 'H', is_ascii=True),
    create_expected_val_test('ḫ', 'h', is_ascii=True),
    create_expected_val_test('Ḭ', 'I', is_ascii=True),
    create_expected_val_test('ḭ', 'i', is_ascii=True),
    create_expected_val_test('Ḯ', 'I', is_ascii=True),
    create_expected_val_test('ḯ', 'i', is_ascii=True),
    create_expected_val_test('Ḱ', 'K', is_ascii=True),
    create_expected_val_test('ḱ', 'k', is_ascii=True),
    create_expected_val_test('Ḳ', 'K', is_ascii=True),
    create_expected_val_test('ḳ', 'k', is_ascii=True),
    create_expected_val_test('Ḵ', 'K', is_ascii=True),
    create_expected_val_test('ḵ', 'k', is_ascii=True),
    create_expected_val_test('Ḷ', 'L', is_ascii=True),
    create_expected_val_test('ḷ', 'l', is_ascii=True),
    create_expected_val_test('Ḹ', 'L', is_ascii=True),
    create_expected_val_test('ḹ', 'l', is_ascii=True),
    create_expected_val_test('Ḻ', 'L', is_ascii=True),
    create_expected_val_test('ḻ', 'l', is_ascii=True),
    create_expected_val_test('Ḽ', 'L', is_ascii=True),
    create_expected_val_test('ḽ', 'l', is_ascii=True),
    create_expected_val_test('Ḿ', 'M', is_ascii=True),
    create_expected_val_test('ḿ', 'm', is_ascii=True),
    create_expected_val_test('Ṁ', 'M', is_ascii=True),
    create_expected_val_test('ṁ', 'm', is_ascii=True),
    create_expected_val_test('Ṃ', 'M', is_ascii=True),
    create_expected_val_test('ṃ', 'm', is_ascii=True),
    create_expected_val_test('Ṅ', 'N', is_ascii=True),
    create_expected_val_test('ṅ', 'n', is_ascii=True),
    create_expected_val_test('Ṇ', 'N', is_ascii=True),
    create_expected_val_test('ṇ', 'n', is_ascii=True),
    create_expected_val_test('Ṉ', 'N', is_ascii=True),
    create_expected_val_test('ṉ', 'n', is_ascii=True),
    create_expected_val_test('Ṋ', 'N', is_ascii=True),
    create_expected_val_test('ṋ', 'n', is_ascii=True),
    create_expected_val_test('Ṍ', 'O', is_ascii=True),
    create_expected_val_test('ṍ', 'o', is_ascii=True),
    create_expected_val_test('Ṏ', 'O', is_ascii=True),
    create_expected_val_test('ṏ', 'o', is_ascii=True),
    create_expected_val_test('Ṑ', 'O', is_ascii=True),
    create_expected_val_test('ṑ', 'o', is_ascii=True),
    create_expected_val_test('Ṓ', 'O', is_ascii=True),
    create_expected_val_test('ṓ', 'o', is_ascii=True),
    create_expected_val_test('Ṕ', 'P', is_ascii=True),
    create_expected_val_test('ṕ', 'p', is_ascii=True),
    create_expected_val_test('Ṗ', 'P', is_ascii=True),
    create_expected_val_test('ṗ', 'p', is_ascii=True),
    create_expected_val_test('Ṙ', 'R', is_ascii=True),
    create_expected_val_test('ṙ', 'r', is_ascii=True),
    create_expected_val_test('Ṛ', 'R', is_ascii=True),
    create_expected_val_test('ṛ', 'r', is_ascii=True),
    create_expected_val_test('Ṝ', 'R', is_ascii=True),
    create_expected_val_test('ṝ', 'r', is_ascii=True),
    create_expected_val_test('Ṟ', 'R', is_ascii=True),
    create_expected_val_test('ṟ', 'r', is_ascii=True),
    create_expected_val_test('Ṡ', 'S', is_ascii=True),
    create_expected_val_test('ṡ', 's', is_ascii=True),
    create_expected_val_test('Ṣ', 'S', is_ascii=True),
    create_expected_val_test('ṣ', 's', is_ascii=True),
    create_expected_val_test('Ṥ', 'S', is_ascii=True),
    create_expected_val_test('ṥ', 's', is_ascii=True),
    create_expected_val_test('Ṧ', 'S', is_ascii=True),
    create_expected_val_test('ṧ', 's', is_ascii=True),
    create_expected_val_test('Ṩ', 'S', is_ascii=True),
    create_expected_val_test('ṩ', 's', is_ascii=True),
    create_expected_val_test('Ṫ', 'T', is_ascii=True),
    create_expected_val_test('ṫ', 't', is_ascii=True),
    create_expected_val_test('Ṭ', 'T', is_ascii=True),
    create_expected_val_test('ṭ', 't', is_ascii=True),
    create_expected_val_test('Ṯ', 'T', is_ascii=True),
    create_expected_val_test('ṯ', 't', is_ascii=True),
    create_expected_val_test('Ṱ', 'T', is_ascii=True),
    create_expected_val_test('ṱ', 't', is_ascii=True),
    create_expected_val_test('Ṳ', 'U', is_ascii=True),
    create_expected_val_test('ṳ', 'u', is_ascii=True),
    create_expected_val_test('Ṵ', 'U', is_ascii=True),
    create_expected_val_test('ṵ', 'u', is_ascii=True),
    create_expected_val_test('Ṷ', 'U', is_ascii=True),
    create_expected_val_test('ṷ', 'u', is_ascii=True),
    create_expected_val_test('Ṹ', 'U', is_ascii=True),
    create_expected_val_test('ṹ', 'u', is_ascii=True),
    create_expected_val_test('Ṻ', 'U', is_ascii=True),
    create_expected_val_test('ṻ', 'u', is_ascii=True),
    create_expected_val_test('Ṽ', 'V', is_ascii=True),
    create_expected_val_test('ṽ', 'v', is_ascii=True),
    create_expected_val_test('Ṿ', 'V', is_ascii=True),
    create_expected_val_test('ṿ', 'v', is_ascii=True),
    create_expected_val_test('Ẁ', 'W', is_ascii=True),
    create_expected_val_test('ẁ', 'w', is_ascii=True),
    create_expected_val_test('Ẃ', 'W', is_ascii=True),
    create_expected_val_test('ẃ', 'w', is_ascii=True),
    create_expected_val_test('Ẅ', 'W', is_ascii=True),
    create_expected_val_test('ẅ', 'w', is_ascii=True),
    create_expected_val_test('Ẇ', 'W', is_ascii=True),
    create_expected_val_test('ẇ', 'w', is_ascii=True),
    create_expected_val_test('Ẉ', 'W', is_ascii=True),
    create_expected_val_test('ẉ', 'w', is_ascii=True),
    create_expected_val_test('Ẋ', 'X', is_ascii=True),
    create_expected_val_test('ẋ', 'x', is_ascii=True),
    create_expected_val_test('Ẍ', 'X', is_ascii=True),
    create_expected_val_test('ẍ', 'x', is_ascii=True),
    create_expected_val_test('Ẏ', 'Y', is_ascii=True),
    create_expected_val_test('ẏ', 'y', is_ascii=True),
    create_expected_val_test('Ẑ', 'Z', is_ascii=True),
    create_expected_val_test('ẑ', 'z', is_ascii=True),
    create_expected_val_test('Ẓ', 'Z', is_ascii=True),
    create_expected_val_test('ẓ', 'z', is_ascii=True),
    create_expected_val_test('Ẕ', 'Z', is_ascii=True),
    create_expected_val_test('ẕ', 'z', is_ascii=True),
    create_expected_val_test('ẖ', 'h', is_ascii=True),
    create_expected_val_test('ẗ', 't', is_ascii=True),
    create_expected_val_test('ẘ', 'w', is_ascii=True),
    create_expected_val_test('ẙ', 'y', is_ascii=True),
    create_expected_val_test('ẚ', 'ẚ'),
    create_expected_val_test('ẛ', 'ſ'),
    create_expected_val_test('ẜ', 'ẜ'),
    create_expected_val_test('ẝ', 'ẝ'),
    create_expected_val_test('ẞ', 'ẞ'),
    create_expected_val_test('ẟ', 'ẟ'),
    create_expected_val_test('Ạ', 'A', is_ascii=True),
    create_expected_val_test('ạ', 'a', is_ascii=True),
    create_expected_val_test('Ả', 'A', is_ascii=True),
    create_expected_val_test('ả', 'a', is_ascii=True),
    create_expected_val_test('Ấ', 'A', is_ascii=True),
    create_expected_val_test('ấ', 'a', is_ascii=True),
    create_expected_val_test('Ầ', 'A', is_ascii=True),
    create_expected_val_test('ầ', 'a', is_ascii=True),
    create_expected_val_test('Ẩ', 'A', is_ascii=True),
    create_expected_val_test('ẩ', 'a', is_ascii=True),
    create_expected_val_test('Ẫ', 'A', is_ascii=True),
    create_expected_val_test('ẫ', 'a', is_ascii=True),
    create_expected_val_test('Ậ', 'A', is_ascii=True),
    create_expected_val_test('ậ', 'a', is_ascii=True),
    create_expected_val_test('Ắ', 'A', is_ascii=True),
    create_expected_val_test('ắ', 'a', is_ascii=True),
    create_expected_val_test('Ằ', 'A', is_ascii=True),
    create_expected_val_test('ằ', 'a', is_ascii=True),
    create_expected_val_test('Ẳ', 'A', is_ascii=True),
    create_expected_val_test('ẳ', 'a', is_ascii=True),
    create_expected_val_test('Ẵ', 'A', is_ascii=True),
    create_expected_val_test('ẵ', 'a', is_ascii=True),
    create_expected_val_test('Ặ', 'A', is_ascii=True),
    create_expected_val_test('ặ', 'a', is_ascii=True),
    create_expected_val_test('Ẹ', 'E', is_ascii=True),
    create_expected_val_test('ẹ', 'e', is_ascii=True),
    create_expected_val_test('Ẻ', 'E', is_ascii=True),
    create_expected_val_test('ẻ', 'e', is_ascii=True),
    create_expected_val_test('Ẽ', 'E', is_ascii=True),
    create_expected_val_test('ẽ', 'e', is_ascii=True),
    create_expected_val_test('Ế', 'E', is_ascii=True),
    create_expected_val_test('ế', 'e', is_ascii=True),
    create_expected_val_test('Ề', 'E', is_ascii=True),
    create_expected_val_test('ề', 'e', is_ascii=True),
    create_expected_val_test('Ể', 'E', is_ascii=True),
    create_expected_val_test('ể', 'e', is_ascii=True),
    create_expected_val_test('Ễ', 'E', is_ascii=True),
    create_expected_val_test('ễ', 'e', is_ascii=True),
    create_expected_val_test('Ệ', 'E', is_ascii=True),
    create_expected_val_test('ệ', 'e', is_ascii=True),
    create_expected_val_test('Ỉ', 'I', is_ascii=True),
    create_expected_val_test('ỉ', 'i', is_ascii=True),
    create_expected_val_test('Ị', 'I', is_ascii=True),
    create_expected_val_test('ị', 'i', is_ascii=True),
    create_expected_val_test('Ọ', 'O', is_ascii=True),
    create_expected_val_test('ọ', 'o', is_ascii=True),
    create_expected_val_test('Ỏ', 'O', is_ascii=True),
    create_expected_val_test('ỏ', 'o', is_ascii=True),
    create_expected_val_test('Ố', 'O', is_ascii=True),
    create_expected_val_test('ố', 'o', is_ascii=True),
    create_expected_val_test('Ồ', 'O', is_ascii=True),
    create_expected_val_test('ồ', 'o', is_ascii=True),
    create_expected_val_test('Ổ', 'O', is_ascii=True),
    create_expected_val_test('ổ', 'o', is_ascii=True),
    create_expected_val_test('Ỗ', 'O', is_ascii=True),
    create_expected_val_test('ỗ', 'o', is_ascii=True),
    create_expected_val_test('Ộ', 'O', is_ascii=True),
    create_expected_val_test('ộ', 'o', is_ascii=True),
    create_expected_val_test('Ớ', 'O', is_ascii=True),
    create_expected_val_test('ớ', 'o', is_ascii=True),
    create_expected_val_test('Ờ', 'O', is_ascii=True),
    create_expected_val_test('ờ', 'o', is_ascii=True),
    create_expected_val_test('Ở', 'O', is_ascii=True),
    create_expected_val_test('ở', 'o', is_ascii=True),
    create_expected_val_test('Ỡ', 'O', is_ascii=True),
    create_expected_val_test('ỡ', 'o', is_ascii=True),
    create_expected_val_test('Ợ', 'O', is_ascii=True),
    create_expected_val_test('ợ', 'o', is_ascii=True),
    create_expected_val_test('Ụ', 'U', is_ascii=True),
    create_expected_val_test('ụ', 'u', is_ascii=True),
    create_expected_val_test('Ủ', 'U', is_ascii=True),
    create_expected_val_test('ủ', 'u', is_ascii=True),
    create_expected_val_test('Ứ', 'U', is_ascii=True),
    create_expected_val_test('ứ', 'u', is_ascii=True),
    create_expected_val_test('Ừ', 'U', is_ascii=True),
    create_expected_val_test('ừ', 'u', is_ascii=True),
    create_expected_val_test('Ử', 'U', is_ascii=True),
    create_expected_val_test('ử', 'u', is_ascii=True),
    create_expected_val_test('Ữ', 'U', is_ascii=True),
    create_expected_val_test('ữ', 'u', is_ascii=True),
    create_expected_val_test('Ự', 'U', is_ascii=True),
    create_expected_val_test('ự', 'u', is_ascii=True),
    create_expected_val_test('Ỳ', 'Y', is_ascii=True),
    create_expected_val_test('ỳ', 'y', is_ascii=True),
    create_expected_val_test('Ỵ', 'Y', is_ascii=True),
    create_expected_val_test('ỵ', 'y', is_ascii=True),
    create_expected_val_test('Ỷ', 'Y', is_ascii=True),
    create_expected_val_test('ỷ', 'y', is_ascii=True),
    create_expected_val_test('Ỹ', 'Y', is_ascii=True),
    create_expected_val_test('ỹ', 'y', is_ascii=True),
    create_expected_val_test('Ỻ', 'Ỻ'),
    create_expected_val_test('ỻ', 'ỻ'),
    create_expected_val_test('Ỽ', 'Ỽ'),
    create_expected_val_test('ỽ', 'ỽ'),
    create_expected_val_test('Ỿ', 'Ỿ'),
    #
    # Ignored code blocks; U+1EFF - U+10FFFF
    #
]
