"""
Django settings for edualert project.

Generated by 'django-admin startproject' using Django 3.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""
import os

import environ

env = environ.Env()
ENVIRONMENT = env.str('ENVIRONMENT', 'local')

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_PATH = environ.Path(__file__) - 3
BASE_DIR = BASE_PATH()


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('DJANGO_SECRET_KEY', default='j&0om)js*ieehwqw0rfo30=cpl_b=!^1u13urgakdt2%*$y6s)')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool('DEBUG', True)

ALLOWED_HOSTS = []

# Application definition

DJANGO_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

THIRD_PARTY_APPS = [
    'rest_framework',
    'corsheaders',
    'oauth2_provider',
    'django_extensions',
    'django_filters',
    'django.contrib.postgres'
]

LOCAL_APPS = [
    'edualert.common',
    'edualert.profiles',
    'edualert.notifications',
    'edualert.schools',
    'edualert.academic_calendars',
    'edualert.academic_programs',
    'edualert.subjects',
    'edualert.study_classes',
    'edualert.catalogs',
    'edualert.statistics'
]

INSTALLED_APPS = DJANGO_APPS + THIRD_PARTY_APPS + LOCAL_APPS


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'edualert.common.middleware.UpdateLastOnlineMiddleware',
]

ROOT_URLCONF = 'edualert.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'edualert.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

DATABASE_URL_KEY = 'DATABASE_URL_STAGING' if ENVIRONMENT == 'staging' else 'DATABASE_URL_PRODUCTION'
DATABASES = {
    'default': env.db(DATABASE_URL_KEY, 'postgres://dbadmin:pass@localhost/edualertdb')
}
DATABASES['default']['CONN_MAX_AGE'] = 500


# REST configurations
REST_FRAMEWORK = {
    'COERCE_DECIMAL_TO_STRING': False,
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'oauth2_provider.contrib.rest_framework.OAuth2Authentication',
        'rest_framework.authentication.SessionAuthentication',
    ),
    'DEFAULT_THROTTLE_RATES': {
        'password-views': '100/minute',
    },
    'DEFAULT_PARSER_CLASSES': (
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.FormParser',
        'rest_framework.parsers.MultiPartParser',
    ),
    'DEFAULT_RENDERER_CLASSES': (
        'edualert.common.renderers.UTF8JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,
    'DEFAULT_FILTER_BACKENDS': (
        'django_filters.rest_framework.DjangoFilterBackend',
    ),
    'TEST_REQUEST_DEFAULT_FORMAT': 'json',
    'DATE_FORMAT': '%d-%m-%Y',
    'DATETIME_FORMAT': '%d-%m-%YT%H:%M:%S',
    'DATE_INPUT_FORMATS': ['%d-%m-%Y'],
    'DATETIME_INPUT_FORMATS': ['%d-%m-%YT%H:%M:%S']
}

AUTHENTICATION_BACKENDS = ['edualert.common.auth_backends.CustomModelBackend']


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

LANGUAGES = (
    ('en-us', 'English'),
    ('ro', 'Romanian')
)

TIME_ZONE = 'UTC'

USE_I18N = True
LOCALE_PATHS = ('locale',)

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'static'),
)
STATIC_ROOT = BASE_PATH('staticfiles')

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_PATH('media')

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'WARNING',
    },
}

DATE_FORMAT = "%d-%m-%Y"
DATETIME_FORMAT = "%d-%m-%YT%H:%M:%S"

FIXTURE_DIRS = (
   BASE_PATH('fixtures'),
)

# CELERY
CELERY_BROKER_URL = env.str('CACHE_URL', '')

# Emails
DEFAULT_FROM_EMAIL = 'dev-no-reply@rodeapps.com'
SERVER_EMAIL = 'dev-no-reply@rodeapps.com'


# Frontend URL
FRONTEND_URL = env.str('FRONTEND_URL_PRODUCTION', 'http://edualert-frontend-dev.herokuapp.com/')
if ENVIRONMENT == 'staging':
    FRONTEND_URL = env.str('FRONTEND_URL_STAGING', '')


# SMS
SEND_SMS = False
if ENVIRONMENT == 'production':
    SEND_SMS = True

WEB2SMS_API_KEY = env.str('WEB2SMS_API_KEY', '')
WEB2SMS_SECRET_KEY = env.str('WEB2SMS_SECRET_KEY', '')
