# Generated by Django 3.0.4 on 2020-03-19 11:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Educator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=180)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
                ('user_role', models.IntegerField(choices=[(1, 'Administrator'), (2, 'School Principal'), (3, 'Teacher'), (4, 'Parent'), (5, 'Student')], help_text='Only user profiles with this role can be assigned to this label.')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_role', models.IntegerField(choices=[(1, 'Administrator'), (2, 'School Principal'), (3, 'Teacher'), (4, 'Parent'), (5, 'Student')])),
                ('username', models.CharField(max_length=150)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.EmailField(blank=True, max_length=150, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('use_phone_as_username', models.BooleanField(default=False)),
                ('email_notifications_enabled', models.BooleanField(default=True)),
                ('sms_notifications_enabled', models.BooleanField(default=False)),
                ('push_notifications_enabled', models.BooleanField(default=True)),
                ('last_logged_in', models.DateTimeField(blank=True, null=True)),
                ('last_change_in_catalog', models.DateTimeField(blank=True, help_text='Only for teachers and school principals.', null=True)),
                ('personal_id_number', models.CharField(blank=True, help_text='Only for students.', max_length=13, null=True)),
                ('is_at_risk', models.BooleanField(default=False, help_text='Only for students.')),
                ('address', models.CharField(blank=True, help_text='Only for students.', max_length=254, null=True)),
                ('birth_date', models.DateField(blank=True, help_text='Only for students.', null=True)),
                ('educator', models.ForeignKey(blank=True, help_text='Only for students.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', related_query_name='student', to='profiles.Educator')),
                ('labels', models.ManyToManyField(blank=True, related_name='user_profile_set', related_query_name='profile', to='profiles.Label')),
                ('parents', models.ManyToManyField(blank=True, help_text='Only for students.', related_name='_userprofile_parents_+', related_query_name='child', to='profiles.UserProfile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
