# Generated by Django 3.0.4 on 2020-03-20 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='school_units',
            field=models.ManyToManyField(related_name='user_profiles', related_query_name='user_profile', to='schools.RegisteredSchoolUnit'),
        ),
    ]
