# Generated by Django 3.0.4 on 2020-03-20 10:45

from django.db import migrations, models
import django.utils.timezone
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
        ('profiles', '0002_userprofile_school_units'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'get_latest_by': 'modified', 'ordering': ('-modified', '-created')},
        ),
        migrations.AddField(
            model_name='userprofile',
            name='created',
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='modified',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='school_units',
            field=models.ManyToManyField(blank=True, related_name='user_profiles', related_query_name='user_profile', to='schools.RegisteredSchoolUnit'),
        ),
    ]
