# Generated by Django 3.0.4 on 2020-03-23 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20200320_1045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='educator',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='last_logged_in',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='educator_email',
            field=models.EmailField(blank=True, help_text='Only for students.', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='educator_full_name',
            field=models.CharField(blank=True, help_text='Only for students.', max_length=180, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='educator_phone_number',
            field=models.CharField(blank=True, help_text='Only for students.', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_online',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='username',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.DeleteModel(
            name='Educator',
        ),
    ]
