# Generated by Django 3.0.4 on 2020-03-24 12:17

from django.db import migrations, models


def set_full_name(apps, schema_editor):
    UserProfile = apps.get_model('profiles', 'UserProfile')

    for profile in UserProfile.objects.all():
        profile.full_name = '{} {}'.format(profile.last_name, profile.first_name)
        profile.save()


def unset_full_name(apps, schema_editor):
    UserProfile = apps.get_model('profiles', 'UserProfile')

    for profile in UserProfile.objects.all():
        names = profile.full_name.split(' ')
        profile.last_name = names[0]
        profile.first_name = names[1]
        profile.save()


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20200323_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, null=True)
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, null=True)
        ),
        migrations.AddField(
            model_name='userprofile',
            name='full_name',
            field=models.CharField(blank=True, max_length=180, null=True),
        ),
        migrations.RunPython(code=set_full_name, reverse_code=unset_full_name),
        migrations.RemoveField(
            model_name='userprofile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='last_name',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='full_name',
            field=models.CharField(max_length=180)
        )
    ]
