# Generated by Django 3.0.4 on 2020-04-01 11:24

from django.contrib.postgres.operations import UnaccentExtension
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_userprofile_student_in_class'),
    ]

    operations = [
        UnaccentExtension(),
        migrations.AlterField(
            model_name='userprofile',
            name='address',
            field=models.CharField(blank=True, help_text='Only for students and parents.', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='username',
            field=models.CharField(help_text='Same username as auth User.', max_length=150, unique=True),
        ),
    ]
