# Generated by Django 3.0.4 on 2020-04-02 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_userprofile_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='parents',
            field=models.ManyToManyField(blank=True, help_text='Only for students.', related_name='children', related_query_name='child', to='profiles.UserProfile'),
        ),
    ]
