# Generated by Django 3.0.4 on 2020-04-09 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0003_auto_20200325_1111'),
        ('profiles', '0010_auto_20200402_0928'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='school_units',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='school_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_profiles', related_query_name='user_profile', to='schools.RegisteredSchoolUnit'),
        ),
    ]
