# Generated by Django 3.0.4 on 2020-04-15 12:38

from django.db import migrations, models
from django.db.models import IntegerChoices, TextChoices


def convert_user_profile_roles(apps, schema_editor):
    UserProfile = apps.get_model('profiles', 'UserProfile')

    class OldUserRoles(IntegerChoices):
        ADMINISTRATOR = 1
        PRINCIPAL = 2
        TEACHER = 3
        PARENT = 4
        STUDENT = 5

    class UserRoles(TextChoices):
        ADMINISTRATOR = 'ADMINISTRATOR'
        PRINCIPAL = 'SCHOOL_PRINCIPAL'
        TEACHER = 'TEACHER'
        PARENT = 'PARENT'
        STUDENT = 'STUDENT'

    for up in UserProfile.objects.all():
        user_role = int(up.user_role)
        if user_role == OldUserRoles.ADMINISTRATOR:
            up.user_role = UserRoles.ADMINISTRATOR
        elif user_role == OldUserRoles.PRINCIPAL:
            up.user_role = UserRoles.PRINCIPAL
        elif user_role == OldUserRoles.TEACHER:
            up.user_role = UserRoles.TEACHER
        elif user_role == OldUserRoles.STUDENT:
            up.user_role = UserRoles.STUDENT
        elif user_role == OldUserRoles.PARENT:
            up.user_role = UserRoles.PARENT

        up.save()


def convert_label_roles(apps, schema_editor):
    Label = apps.get_model('profiles', 'Label')

    class OldUserRoles(IntegerChoices):
        ADMINISTRATOR = 1
        PRINCIPAL = 2
        TEACHER = 3
        PARENT = 4
        STUDENT = 5

    class UserRoles(TextChoices):
        ADMINISTRATOR = 'ADMINISTRATOR'
        PRINCIPAL = 'SCHOOL_PRINCIPAL'
        TEACHER = 'TEACHER'
        PARENT = 'PARENT'
        STUDENT = 'STUDENT'

    for label in Label.objects.all():
        user_role = int(label.user_role)
        if user_role == OldUserRoles.ADMINISTRATOR:
            label.user_role = UserRoles.ADMINISTRATOR
        elif user_role == OldUserRoles.PRINCIPAL:
            label.user_role = UserRoles.PRINCIPAL
        elif user_role == OldUserRoles.TEACHER:
            label.user_role = UserRoles.TEACHER
        elif user_role == OldUserRoles.STUDENT:
            label.user_role = UserRoles.STUDENT
        elif user_role == OldUserRoles.PARENT:
            label.user_role = UserRoles.PARENT

        label.save()


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_auto_20200409_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_role',
            field=models.CharField(choices=[('ADMINISTRATOR', 'Administrator'), ('SCHOOL_PRINCIPAL', 'School Principal'), ('TEACHER', 'Teacher'), ('PARENT', 'Parent'), ('STUDENT', 'Student')],
                                   max_length=100),
        ),
        migrations.AlterField(
            model_name='label',
            name='user_role',
            field=models.CharField(choices=[('ADMINISTRATOR', 'Administrator'), ('SCHOOL_PRINCIPAL', 'School Principal'), ('TEACHER', 'Teacher'), ('PARENT', 'Parent'), ('STUDENT', 'Student')],
                                   help_text='Only user profiles with this role can be assigned to this label.', max_length=100),
        ),
        migrations.RunPython(code=convert_label_roles, reverse_code=migrations.RunPython.noop),
        migrations.RunPython(code=convert_user_profile_roles, reverse_code=migrations.RunPython.noop),
    ]
