# Generated by Django 3.0.4 on 2020-05-13 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0011_auto_20200508_1357'),
        ('profiles', '0013_auto_20200504_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='taught_subjects',
            field=models.ManyToManyField(blank=True, help_text='Only for teachers.', related_name='teachers', to='subjects.Subject'),
        ),
    ]
