# Generated by Django 3.0.4 on 2020-06-19 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0014_auto_20200513_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='label',
            name='is_label_for_transfers_between_schools',
            field=models.BooleanField(default=False),
        ),
    ]
