# Generated by Django 3.0.4 on 2020-06-23 10:04

from django.db import migrations


def add_labels(apps, schema_editor):
    Label = apps.get_model('profiles', 'Label')
    Label.objects.all().delete()

    student_labels = ['Transferat', 'Exmatriculat', 'Risc Abandon 1', 'Risc Abandon 2', 'Abandon',
                      'Corigent 1 Materie', 'Corigent 2 Materii', 'Repetent', 'Repetent Caz Boală',
                      'Scutit Educație Fizică', 'Scutit Religie', 'Înregistrat Proiect ORS - Grup Suport',
                      'Înregistrat Proiect ORS - Mentoring', 'Înregistrat Proiect ORS - Workshop',
                      'Înregistrat Proiect ORS - Summer Camp', 'Consiliere Psihologică']
    for student_label in student_labels:
        label = Label.objects.create(text=student_label, user_role='STUDENT')
        if student_label == 'Transferat':
            label.is_label_for_transfers_between_schools = True
            label.save()


class Migration(migrations.Migration):
    dependencies = [
        ('profiles', '0015_label_is_label_for_transfers_between_schools'),
    ]

    operations = [
        migrations.RunPython(code=add_labels, reverse_code=migrations.RunPython.noop),
    ]
