# Generated by Django 3.0.4 on 2020-10-27 13:45

from django.db import migrations, models


def set_sms_notifications_enabled(apps, schema_editor):
    UserProfile = apps.get_model('profiles', 'UserProfile')
    UserProfile.objects.update(sms_notifications_enabled=True)


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0017_userprofile_risk_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='sms_notifications_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.RunPython(code=set_sms_notifications_enabled, reverse_code=migrations.RunPython.noop),
    ]
