# Generated by Django 3.0.4 on 2020-05-04 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0002_auto_20200410_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examinationgrade',
            name='subject_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='studentcatalogpersubject',
            name='subject_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='subjectabsence',
            name='subject_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='subjectgrade',
            name='subject_name',
            field=models.CharField(max_length=100),
        ),
    ]
