# Generated by Django 3.0.4 on 2020-05-13 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0003_auto_20200504_1339'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentcatalogpersubject',
            old_name='has_simulation',
            new_name='wants_simulation',
        ),
        migrations.RenameField(
            model_name='studentcatalogpersubject',
            old_name='has_thesis',
            new_name='wants_thesis',
        ),
    ]
