# Generated by Django 3.0.4 on 2020-05-15 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0005_examinationgrade_grade_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='examinationgrade',
            options={'ordering': ['-taken_at']},
        ),
        migrations.AlterModelOptions(
            name='subjectabsence',
            options={'ordering': ['-taken_at']},
        ),
        migrations.AlterModelOptions(
            name='subjectgrade',
            options={'ordering': ['-taken_at']},
        ),
    ]
