# Generated by Django 3.0.4 on 2020-05-15 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0006_auto_20200515_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='examinationgrade',
            name='semester',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Only for Diference grades.', null=True),
        ),
    ]
