# Generated by Django 3.0.4 on 2020-05-25 09:38

from django.db import migrations, models


def set_catalog_absences(apps, schema_editor):
    StudentCatalogPerSubject = apps.get_model('catalogs', 'studentcatalogpersubject')
    StudentCatalogPerYear = apps.get_model('catalogs', 'studentcatalogperyear')

    for catalog in StudentCatalogPerSubject.objects.all():
        catalog.abs_count_sem1 = 0
        catalog.abs_count_sem2 = 0
        catalog.abs_count_annual = 0
        catalog.unfounded_abs_count_sem1 = 0
        catalog.unfounded_abs_count_sem2 = 0
        catalog.unfounded_abs_count_annual = 0
        catalog.founded_abs_count_sem1 = 0
        catalog.founded_abs_count_sem2 = 0
        catalog.founded_abs_count_annual = 0
        catalog.save()

    for catalog in StudentCatalogPerYear.objects.all():
        catalog.abs_count_sem1 = 0
        catalog.abs_count_sem2 = 0
        catalog.abs_count_annual = 0
        catalog.unfounded_abs_count_sem1 = 0
        catalog.unfounded_abs_count_sem2 = 0
        catalog.unfounded_abs_count_annual = 0
        catalog.founded_abs_count_sem1 = 0
        catalog.founded_abs_count_sem2 = 0
        catalog.founded_abs_count_annual = 0
        catalog.save()


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0009_auto_20200519_1419'),
    ]

    operations = [
        migrations.RunPython(code=set_catalog_absences, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='studentcatalogpersubject',
            name='abs_count_annual',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='studentcatalogpersubject',
            name='abs_count_sem1',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='studentcatalogpersubject',
            name='abs_count_sem2',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='studentcatalogpersubject',
            name='founded_abs_count_annual',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='studentcatalogpersubject',
            name='founded_abs_count_sem1',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='studentcatalogpersubject',
            name='founded_abs_count_sem2',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='studentcatalogpersubject',
            name='unfounded_abs_count_annual',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='studentcatalogpersubject',
            name='unfounded_abs_count_sem1',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='studentcatalogpersubject',
            name='unfounded_abs_count_sem2',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='studentcatalogperyear',
            name='abs_count_annual',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='studentcatalogperyear',
            name='abs_count_sem1',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='studentcatalogperyear',
            name='abs_count_sem2',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='studentcatalogperyear',
            name='founded_abs_count_annual',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='studentcatalogperyear',
            name='founded_abs_count_sem1',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='studentcatalogperyear',
            name='founded_abs_count_sem2',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='studentcatalogperyear',
            name='unfounded_abs_count_annual',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='studentcatalogperyear',
            name='unfounded_abs_count_sem1',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='studentcatalogperyear',
            name='unfounded_abs_count_sem2',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
