# Generated by Django 3.0.4 on 2020-06-12 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0014_auto_20200513_1451'),
        ('catalogs', '0013_auto_20200529_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentcatalogpersubject',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teacher_catalogs_per_subject', related_query_name='teacher_catalog_per_subject', to='profiles.UserProfile'),
        ),
    ]
