# Generated by Django 3.0.4 on 2020-03-31 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0003_auto_20200325_1111'),
        ('profiles', '0006_userprofile_taught_subjects'),
        ('academic_programs', '0002_auto_20200331_1213'),
        ('subjects', '0003_auto_20200331_1238'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_program_name', models.CharField(blank=True, max_length=64, null=True)),
                ('academic_year', models.PositiveSmallIntegerField()),
                ('class_grade', models.CharField(help_text='The roman number of the class.', max_length=3)),
                ('class_grade_arabic', models.PositiveSmallIntegerField()),
                ('class_letter', models.CharField(max_length=1)),
                ('students_at_risk_count', models.PositiveSmallIntegerField(default=0)),
                ('avg_sem1', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('avg_sem2', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('avg_annual', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('unfounded_abs_avg_sem1', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('unfounded_abs_avg_sem2', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('unfounded_abs_avg_annual', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('academic_program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='study_classes', related_query_name='study_class', to='academic_programs.AcademicProgram')),
                ('class_master', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='mastering_study_class', to='profiles.UserProfile')),
                ('school_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_classes', related_query_name='study_class', to='schools.RegisteredSchoolUnit')),
            ],
        ),
        migrations.CreateModel(
            name='TeacherClassThrough',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_class_master', models.BooleanField(default=False)),
                ('academic_year', models.PositiveSmallIntegerField()),
                ('class_grade', models.CharField(help_text='The roman number of the class.', max_length=3)),
                ('class_letter', models.CharField(max_length=1)),
                ('academic_program_name', models.CharField(blank=True, max_length=64, null=True)),
                ('subject_name', models.CharField(max_length=64)),
                ('is_optional_subject', models.BooleanField(default=False)),
                ('is_coordination_subject', models.BooleanField(default=False)),
                ('study_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_class_through', to='study_classes.StudyClass')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_class_through', to='subjects.Subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_class_through', to='profiles.UserProfile')),
            ],
        ),
        migrations.AddField(
            model_name='studyclass',
            name='teachers',
            field=models.ManyToManyField(related_name='study_classes', related_query_name='study_class', through='study_classes.TeacherClassThrough', to='profiles.UserProfile'),
        ),
    ]
