# Generated by Django 3.0.4 on 2020-04-13 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_classes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyclass',
            name='class_grade',
            field=models.CharField(help_text='The roman number of the class.', max_length=4),
        ),
        migrations.AlterField(
            model_name='teacherclassthrough',
            name='class_grade',
            field=models.CharField(help_text='The roman number of the class.', max_length=4),
        ),
    ]
