# Generated by Django 3.0.4 on 2020-04-16 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_classes', '0002_auto_20200413_0914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyclass',
            name='academic_program_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='teacherclassthrough',
            name='academic_program_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
