# Generated by Django 3.0.4 on 2020-04-16 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study_classes', '0003_auto_20200416_1040'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studyclass',
            options={'ordering': ('class_grade_arabic', 'class_letter')},
        ),
    ]
