# Generated by Django 3.0.4 on 2020-04-21 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0012_auto_20200415_1238'),
        ('study_classes', '0004_auto_20200416_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyclass',
            name='class_master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mastering_study_classes', related_query_name='mastering_study_classes', to='profiles.UserProfile'),
        ),
    ]
