# Generated by Django 3.0.4 on 2020-04-22 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study_classes', '0005_auto_20200421_1453'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studyclass',
            options={'ordering': ('class_grade_arabic', 'class_letter'), 'verbose_name_plural': 'study classes'},
        ),
    ]
