# Generated by Django 3.0.4 on 2020-06-12 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0014_auto_20200513_1451'),
        ('study_classes', '0007_auto_20200504_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherclassthrough',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teacher_class_through', to='profiles.UserProfile'),
        ),
    ]
