# Generated by Django 3.0.4 on 2020-10-02 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_classes', '0008_auto_20200612_0855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyclass',
            name='class_letter',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='teacherclassthrough',
            name='class_letter',
            field=models.CharField(max_length=3),
        ),
    ]
