# Generated by Django 3.0.4 on 2020-03-20 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('district', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='SchoolUnitCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
            options={'verbose_name_plural': 'School unit categories'}
        ),
        migrations.CreateModel(
            name='RegisteredSchoolUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('academic_profile', models.CharField(blank=True, max_length=64, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('district', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=64)),
                ('address', models.CharField(max_length=254)),
                ('email', models.EmailField(max_length=150)),
                ('phone_number', models.CharField(max_length=20)),
                ('students_at_risk_count', models.PositiveSmallIntegerField(default=0)),
                ('last_change_in_catalog', models.DateTimeField(blank=True, null=True)),
                ('categories', models.ManyToManyField(related_name='registered_school_units', related_query_name='registered_school_unit', to='schools.SchoolUnitCategory')),
                ('school_principal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registered_school_units', related_query_name='registered_school_units', to='profiles.UserProfile')),
            ],
        ),
    ]
