# Generated by Django 3.0.4 on 2020-03-20 10:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20200320_1045'),
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registeredschoolunit',
            options={'get_latest_by': 'modified', 'ordering': ('-modified', '-created')},
        ),
        migrations.AddField(
            model_name='registeredschoolunit',
            name='created',
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registeredschoolunit',
            name='modified',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified'),
        ),
        migrations.AlterField(
            model_name='registeredschoolunit',
            name='school_principal',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='registered_school_unit', to='profiles.UserProfile'),
        ),
    ]
