# Generated by Django 3.0.4 on 2020-03-25 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_auto_20200320_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeredschoolunit',
            name='city',
            field=models.CharField(db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='registeredschoolunit',
            name='district',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='schoolunit',
            name='city',
            field=models.CharField(db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='schoolunit',
            name='district',
            field=models.CharField(db_index=True, max_length=20),
        ),
    ]
