# Generated by Django 3.0.4 on 2020-04-14 16:04

from django.db import migrations, models
import django.db.models.deletion


def set_academic_profile_null(apps, schema_editor):
    RegisteredSchoolUnit = apps.get_model('schools', 'RegisteredSchoolUnit')
    for school in RegisteredSchoolUnit.objects.all():
        school.academic_profile = None
        school.save()


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0003_auto_20200325_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolunitcategory',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.CreateModel(
            name='SchoolUnitProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_profiles', related_query_name='academic_profile', to='schools.SchoolUnitCategory')),
            ],
        ),
        migrations.RunPython(code=set_academic_profile_null, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='registeredschoolunit',
            name='academic_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_school_units', related_query_name='registered_school_unit', to='schools.SchoolUnitProfile'),
        ),
    ]
