# Generated by Django 3.0.4 on 2020-04-22 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0004_auto_20200414_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolunitcategory',
            name='category_level',
            field=models.CharField(choices=[('PRIMARY_SCHOOL', 'Primary school'), ('SECONDARY_SCHOOL', 'Secondary school'), ('HIGHSCHOOL', 'Highschool')], default='HIGHSCHOOL', max_length=64),
            preserve_default=False,
        ),
    ]
