# Generated by Django 3.0.4 on 2020-04-23 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0008_categorysubjectthrough'),
        ('schools', '0005_schoolunitcategory_category_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolunitcategory',
            name='subjects',
            field=models.ManyToManyField(blank=True, related_name='school_categories', related_query_name='school_category', through='subjects.CategorySubjectThrough', to='subjects.Subject'),
        ),
    ]
