# Generated by Django 3.0.4 on 2020-03-31 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0003_auto_20200325_1111'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenericAcademicProgram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('academic_profile', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='AcademicProgram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('academic_year', models.PositiveSmallIntegerField()),
                ('classes_count', models.PositiveSmallIntegerField(default=0)),
                ('students_at_risk_count', models.PositiveSmallIntegerField(default=0)),
                ('avg_sem1', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('avg_sem2', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('avg_annual', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('unfounded_abs_avg_sem1', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('unfounded_abs_avg_sem2', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('unfounded_abs_avg_annual', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('generic_academic_program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_programs', to='academic_programs.GenericAcademicProgram')),
                ('school_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_programs', related_query_name='academic_program', to='schools.RegisteredSchoolUnit')),
            ],
        ),
    ]
