# Generated by Django 3.0.4 on 2020-03-31 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0002_programsubjectthrough'),
        ('academic_programs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicprogram',
            name='optional_subjects',
            field=models.ManyToManyField(blank=True, related_name='academic_programs', related_query_name='academic_program', through='subjects.ProgramSubjectThrough', to='subjects.Subject'),
        ),
        migrations.AddField(
            model_name='genericacademicprogram',
            name='mandatory_subjects',
            field=models.ManyToManyField(related_name='generic_academic_programs', related_query_name='generic_academic_program', through='subjects.ProgramSubjectThrough', to='subjects.Subject'),
        ),
    ]
