# Generated by Django 3.0.4 on 2020-04-07 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic_programs', '0002_auto_20200331_1213'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='academicprogram',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='genericacademicprogram',
            options={'ordering': ('name',)},
        ),
    ]
