# Generated by Django 3.0.4 on 2020-04-14 16:08

from django.db import migrations, models
import django.db.models.deletion


def set_academic_profile_null(apps, schema_editor):
    GenericAcademicProgram = apps.get_model('academic_programs', 'GenericAcademicProgram')
    for program in GenericAcademicProgram.objects.all():
        program.academic_profile = None
        program.save()


def set_academic_profile_value(apps, schema_editor):
    GenericAcademicProgram = apps.get_model('academic_programs', 'GenericAcademicProgram')
    for program in GenericAcademicProgram.objects.all():
        program.academic_profile = 'muzica'
        program.save()


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0004_auto_20200414_1604'),
        ('academic_programs', '0003_auto_20200407_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='genericacademicprogram',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generic_academic_programs', related_query_name='generic_academic_program', to='schools.SchoolUnitCategory'),
        ),
        migrations.AlterField(
            model_name='genericacademicprogram',
            name='academic_profile',
            field=models.CharField(blank=True, null=True, max_length=64),
        ),
        migrations.RunPython(code=set_academic_profile_null, reverse_code=set_academic_profile_value),
        migrations.AlterField(
            model_name='genericacademicprogram',
            name='academic_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generic_academic_programs', related_query_name='generic_academic_program', to='schools.SchoolUnitProfile'),
        ),
    ]
