# Generated by Django 3.0.4 on 2020-04-16 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_programs', '0004_auto_20200414_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicprogram',
            name='name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='genericacademicprogram',
            name='name',
            field=models.CharField(max_length=128),
        ),
    ]
