# Generated by Django 3.0.4 on 2020-04-22 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_programs', '0005_auto_20200416_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='genericacademicprogram',
            name='optional_subjects_weekly_hours',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
