# Generated by Django 3.0.4 on 2020-04-30 10:37

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic_programs', '0006_genericacademicprogram_optional_subjects_weekly_hours'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genericacademicprogram',
            name='optional_subjects_weekly_hours',
        ),
        migrations.AddField(
            model_name='genericacademicprogram',
            name='optional_subjects_weekly_hours',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
