# Generated by Django 3.0.4 on 2020-05-08 13:57

from django.db import migrations
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('academic_programs', '0007_auto_20200430_1037'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='academicprogram',
            options={'ordering': (django.db.models.functions.text.Lower('name'),)},
        ),
        migrations.AlterModelOptions(
            name='genericacademicprogram',
            options={'ordering': (django.db.models.functions.text.Lower('name'),)},
        ),
    ]
