# Generated by Django 3.0.4 on 2020-06-16 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0015_remove_programsubjectthrough_is_core_subject'),
        ('academic_programs', '0008_auto_20200508_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicprogram',
            name='core_subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_academic_programs', related_query_name='main_academic_program', to='subjects.Subject'),
        ),
    ]
