# Generated by Django 3.0.4 on 2020-04-03 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic_calendars', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schoolevent',
            options={'ordering': ['starts_at']},
        ),
    ]
