# Generated by Django 3.0.4 on 2020-04-09 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic_calendars', '0002_auto_20200403_0928'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolevent',
            name='academic_year_calendar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='school_events', to='academic_calendars.AcademicYearCalendar'),
        ),
        migrations.AlterField(
            model_name='schoolevent',
            name='semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='school_events', to='academic_calendars.SemesterCalendar'),
        ),
        migrations.AlterField(
            model_name='schoolevent',
            name='event_type',
            field=models.IntegerField(choices=[(1, 'Second semester end eighth grade'), (2, 'Second semester end twelfth grade'), (3, 'Second semester end IX-XI, Filiera Tehnologica'),
                                               (4, 'Autumn break for the I-IV classes.'), (5, 'Winter holiday'), (6, 'Spring holiday'), (7, 'Legal/Public holiday'), (8, 'Corigente'),
                                               (9, 'Diferente')]),
        ),
    ]
