# Generated by Django 3.0.4 on 2020-04-15 12:14

from django.db import migrations, models
from django.db.models import IntegerChoices, TextChoices


def convert_event_types(apps, schema_editor):
    SchoolEvent = apps.get_model('academic_calendars', 'SchoolEvent')

    class OldEventTypes(IntegerChoices):
        SECOND_SEMESTER_END_VIII_GRADE = 1
        SECOND_SEMESTER_END_XII_XIII_GRADE = 2
        SECOND_SEMESTER_END_IX_XI_FILIERA_TEOLOGICA = 3
        I_IV_GRADES_AUTUMN_HOLIDAY = 4
        WINTER_HOLIDAY = 5
        SPRING_HOLIDAY = 6
        LEGAL_PUBLIC_HOLIDAY = 7
        CORIGENTE = 8
        DIFERENTE = 9

    class NewEventTypes(TextChoices):
        SECOND_SEMESTER_END_VIII_GRADE = 'SECOND_SEMESTER_END_VIII_GRADE'
        SECOND_SEMESTER_END_XII_XIII_GRADE = 'SECOND_SEMESTER_END_XII_XIII_GRADE'
        SECOND_SEMESTER_END_IX_XI_FILIERA_TEOLOGICA = 'SECOND_SEMESTER_END_IX_XI_FILIERA_TEOLOGICA'
        I_IV_GRADES_AUTUMN_HOLIDAY = 'I_IV_GRADES_AUTUMN_HOLIDAY'
        WINTER_HOLIDAY = 'WINTER_HOLIDAY'
        SPRING_HOLIDAY = 'SPRING_HOLIDAY'
        LEGAL_PUBLIC_HOLIDAY = 'LEGAL_PUBLIC_HOLIDAY'
        CORIGENTE = 'CORIGENTE'
        DIFERENTE = 'DIFERENTE'

    for event in SchoolEvent.objects.all():
        event_type = int(event.event_type)

        events_mapping = {
            OldEventTypes.SECOND_SEMESTER_END_VIII_GRADE: NewEventTypes.SECOND_SEMESTER_END_VIII_GRADE,
            OldEventTypes.SECOND_SEMESTER_END_XII_XIII_GRADE: NewEventTypes.SECOND_SEMESTER_END_XII_XIII_GRADE,
            OldEventTypes.SECOND_SEMESTER_END_IX_XI_FILIERA_TEOLOGICA: NewEventTypes.SECOND_SEMESTER_END_IX_XI_FILIERA_TEOLOGICA,
            OldEventTypes.I_IV_GRADES_AUTUMN_HOLIDAY: NewEventTypes.I_IV_GRADES_AUTUMN_HOLIDAY,
            OldEventTypes.WINTER_HOLIDAY: NewEventTypes.WINTER_HOLIDAY,
            OldEventTypes.SPRING_HOLIDAY: NewEventTypes.SPRING_HOLIDAY,
            OldEventTypes.LEGAL_PUBLIC_HOLIDAY: NewEventTypes.LEGAL_PUBLIC_HOLIDAY,
            OldEventTypes.CORIGENTE: NewEventTypes.CORIGENTE,
            OldEventTypes.DIFERENTE: NewEventTypes.DIFERENTE
        }

        event.event_type = events_mapping[event_type]
        event.save()


class Migration(migrations.Migration):
    dependencies = [
        ('academic_calendars', '0005_auto_20200414_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolevent',
            name='event_type',
            field=models.CharField(choices=[('SECOND_SEMESTER_END_VIII_GRADE', 'Semester II end for VIII grade'),
                                            ('SECOND_SEMESTER_END_XII_XIII_GRADE', "Semester II end for XII & XIII grade ('seral & frecvență redusă')"),
                                            ('SECOND_SEMESTER_END_IX_XI_FILIERA_TEOLOGICA', "Semester II end for IX-XI grades, profile 'Filieră Tehnologică'"),
                                            ('I_IV_GRADES_AUTUMN_HOLIDAY', 'I-IV grades autumn holiday'), ('WINTER_HOLIDAY', 'Winter holiday'), ('SPRING_HOLIDAY', 'Spring holiday'),
                                            ('LEGAL_PUBLIC_HOLIDAY', 'Legal/Public holiday'), ('CORIGENTE', 'Corigente'), ('DIFERENTE', 'Diferente')],
                                   max_length=64),
        ),
        migrations.RunPython(code=convert_event_types, reverse_code=migrations.RunPython.noop)
    ]
