# Generated by Django 3.0.4 on 2020-04-22 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_calendars', '0006_auto_20200415_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolevent',
            name='event_type',
            field=models.CharField(choices=[('SECOND_SEMESTER_END_VIII_GRADE', 'Semester II end for VIII grade'), ('SECOND_SEMESTER_END_XII_XIII_GRADE', "Semester II end for XII & XIII grade ('seral & frecvență redusă')"), ('SECOND_SEMESTER_END_IX_XI_FILIERA_TEHNOLOGICA', "Semester II end for IX-XI grades, profile 'Filieră Tehnologică'"), ('I_IV_GRADES_AUTUMN_HOLIDAY', 'I-IV grades autumn holiday'), ('WINTER_HOLIDAY', 'Winter holiday'), ('SPRING_HOLIDAY', 'Spring holiday'), ('LEGAL_PUBLIC_HOLIDAY', 'Legal/Public holiday'), ('CORIGENTE', 'Corigente'), ('DIFERENTE', 'Diferente')], max_length=64),
        ),
    ]
