# Generated by Django 3.0.4 on 2020-05-22 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_calendars', '0007_auto_20200422_0838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicyearcalendar',
            name='academic_year',
            field=models.PositiveSmallIntegerField(unique=True),
        ),
    ]
