# Generated by Django 3.0.4 on 2020-05-28 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_calendars', '0008_auto_20200522_0905'),
    ]

    operations = [
        migrations.AddField(
            model_name='semestercalendar',
            name='working_weeks_count',
            field=models.PositiveSmallIntegerField(default=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='semestercalendar',
            name='working_weeks_count_12_grade',
            field=models.PositiveSmallIntegerField(default=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='semestercalendar',
            name='working_weeks_count_8_grade',
            field=models.PositiveSmallIntegerField(default=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='semestercalendar',
            name='working_weeks_count_technological',
            field=models.PositiveSmallIntegerField(default=15),
            preserve_default=False,
        ),
    ]
