# Generated by Django 3.0.4 on 2020-06-02 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_calendars', '0009_auto_20200528_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='semestercalendar',
            name='working_weeks_count_primary_school',
            field=models.PositiveSmallIntegerField(default=15),
            preserve_default=False,
        ),
    ]
