# Generated by Django 3.0.4 on 2020-04-01 09:56

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0007_userprofile_student_in_class'),
        ('study_classes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('title', models.CharField(max_length=64)),
                ('body', models.TextField()),
                ('send_sms', models.BooleanField(default=False)),
                ('from_user_full_name', models.CharField(max_length=180)),
                ('from_user_role', models.IntegerField(choices=[(1, 'Administrator'), (2, 'School Principal'), (3, 'Teacher'), (4, 'Parent'), (5, 'Student')])),
                ('from_user_subjects', models.CharField(blank=True, help_text="Concatenated list of sender's taught subjects.", max_length=180, null=True)),
                ('receiver_type', models.IntegerField(choices=[(1, 'Class students'), (2, 'Class parents'), (3, 'Single student'), (4, 'Single parent')])),
                ('target_users_role', models.IntegerField(choices=[(1, 'Administrator'), (2, 'School Principal'), (3, 'Teacher'), (4, 'Parent'), (5, 'Student')])),
                ('target_study_class_grade', models.CharField(max_length=3)),
                ('target_study_class_letter', models.CharField(max_length=1)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_notifications', related_query_name='sent_notification', to='profiles.UserProfile')),
                ('target_study_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_notifications', related_query_name='received_notification', to='study_classes.StudyClass')),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TargetUserThrough',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_profile_full_name', models.CharField(max_length=180)),
                ('is_read', models.BooleanField(default=False)),
                ('child_full_name', models.CharField(blank=True, help_text='Only if the target is one parent.', max_length=180, null=True)),
                ('child', models.ForeignKey(blank=True, help_text='Only if the target is one parent.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='profiles.UserProfile')),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_users_through', related_query_name='target_user_through', to='notifications.Notification')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_users_through', related_query_name='target_user_through', to='profiles.UserProfile')),
            ],
        ),
        migrations.AddField(
            model_name='notification',
            name='target_users',
            field=models.ManyToManyField(related_name='received_notifications', related_query_name='received_notification', through='notifications.TargetUserThrough', to='profiles.UserProfile'),
        ),
    ]
