# Generated by Django 3.0.4 on 2020-04-01 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='targetuserthrough',
            name='sent_at_email',
            field=models.EmailField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='targetuserthrough',
            name='sent_at_phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
