# Generated by Django 3.0.4 on 2020-04-13 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_auto_20200401_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='target_study_class_grade',
            field=models.CharField(max_length=4),
        ),
    ]
