# Generated by Django 3.0.4 on 2020-04-15 12:20

from django.db import migrations, models
from django.db.models import IntegerChoices, TextChoices


def convert_notification_roles(apps, schema_editor):
    Notification = apps.get_model('notifications', 'Notification')

    class OldUserRoles(IntegerChoices):
        ADMINISTRATOR = 1
        PRINCIPAL = 2
        TEACHER = 3
        PARENT = 4
        STUDENT = 5

    class UserRoles(TextChoices):
        ADMINISTRATOR = 'ADMINISTRATOR'
        PRINCIPAL = 'SCHOOL_PRINCIPAL'
        TEACHER = 'TEACHER'
        PARENT = 'PARENT'
        STUDENT = 'STUDENT'

    for notification in Notification.objects.all():
        from_user_role = int(notification.from_user_role)
        target_users_role = int(notification.target_users_role)

        if from_user_role == OldUserRoles.ADMINISTRATOR:
            notification.target_users_role = UserRoles.ADMINISTRATOR
        elif from_user_role == OldUserRoles.PRINCIPAL:
            notification.target_users_role = UserRoles.PRINCIPAL
        elif from_user_role == OldUserRoles.TEACHER:
            notification.target_users_role = UserRoles.TEACHER
        elif from_user_role == OldUserRoles.STUDENT:
            notification.target_users_role = UserRoles.STUDENT
        elif from_user_role == OldUserRoles.PARENT:
            notification.target_users_role = UserRoles.PARENT

        if target_users_role == OldUserRoles.ADMINISTRATOR:
            notification.target_users_role = UserRoles.ADMINISTRATOR
        elif target_users_role == OldUserRoles.PRINCIPAL:
            notification.target_users_role = UserRoles.PRINCIPAL
        elif target_users_role == OldUserRoles.TEACHER:
            notification.target_users_role = UserRoles.TEACHER
        elif target_users_role == OldUserRoles.STUDENT:
            notification.target_users_role = UserRoles.STUDENT
        elif target_users_role == OldUserRoles.PARENT:
            notification.target_users_role = UserRoles.PARENT

        notification.save()


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_auto_20200413_0914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='from_user_role',
            field=models.CharField(choices=[('ADMINISTRATOR', 'Administrator'), ('SCHOOL_PRINCIPAL', 'School Principal'), ('TEACHER', 'Teacher'), ('PARENT', 'Parent'), ('STUDENT', 'Student')], max_length=100),
        ),
        migrations.AlterField(
            model_name='notification',
            name='target_users_role',
            field=models.CharField(choices=[('ADMINISTRATOR', 'Administrator'), ('SCHOOL_PRINCIPAL', 'School Principal'), ('TEACHER', 'Teacher'), ('PARENT', 'Parent'), ('STUDENT', 'Student')], max_length=100),
        ),
        migrations.RunPython(code=convert_notification_roles, reverse_code=migrations.RunPython.noop)
    ]
