# Generated by Django 3.0.4 on 2020-04-28 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_auto_20200428_1321'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ('-created',)},
        ),
        migrations.AddField(
            model_name='notification',
            name='targets_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='notification',
            name='receiver_type',
            field=models.CharField(choices=[('CLASS_STUDENTS', 'Class students'), ('CLASS_PARENTS', 'Class parents'), ('ONE_STUDENT', 'One student'), ('ONE_PARENT', 'One parent')], max_length=64),
        ),
    ]
