# Generated by Django 3.0.4 on 2020-05-04 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0007_auto_20200429_0832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='from_user_subjects',
            field=models.TextField(blank=True, help_text="Concatenated list of sender's taught subjects.", null=True),
        ),
    ]
