name: build-and-deploy

on:
  push:
    branches:
      - staging
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        shell: bash
        env:
          SECRET_VARIABLES: ${{ secrets.SECRET_VARIABLES }}
        run: |
          TAG=$(echo ${GITHUB_REF#refs/heads/} | sed -r 's/\//-/g' | tr '[:upper:]' '[:lower:]')-${GITHUB_SHA::8}
          export TAG $(echo ${SECRET_VARIABLES})

          bash docker-config/app/build.sh
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - name: Deploy
        shell: bash
        env:
          SECRET_VARIABLES: ${{ secrets.SECRET_VARIABLES }}
        run: |
          BRANCH_NAME=${GITHUB_REF#refs/heads/}
          [[ "${BRANCH_NAME}" = "staging" ]] && ENVIRONMENT=staging
          [[ "${BRANCH_NAME}" = "master" ]] && ENVIRONMENT=production

          TAG=$(echo ${BRANCH_NAME} | sed -r 's/\//-/g' | tr '[:upper:]' '[:lower:]')-${GITHUB_SHA::8}
          export $(echo ${SECRET_VARIABLES}) ENVIRONMENT TAG TASK_DEFINITION=app

          bash scripts/deploy-service.sh
